Backfill pipeline updates
anyfin/anyfin-platform pull request #19
Opened 2022-02-22 12:41 UTC by csioa

2022-02-22 16:06 UTC, malcolmtivelius commented on anyfin-platform/platform-composer/dags/cloudsql_to_bigquery/export_bq_backfill.py
> +		daily_load = True if table_name in daily_tables else False
On row 88 we generate daily_tables from the backfill.get_export_tables() function. However here we are iterating over .get_beam_export_tables(). So in case the tables are beam_export instead of nested or direct, wont daily_tables be empty in this case? Or the other way around, daily_tables will have tables but get beam export will return empty

2022-02-22 16:08 UTC, malcolmtivelius commented on anyfin-platform/platform-composer/dags/cloudsql_to_bigquery/export_bq_backfill.py
> +			prod as (SELECT DATE(created_at) dt, count(*) cnt FROM `anyfin.{DATABASE_NAME}.{table_name}` group by 1),
Shouldnt this check be against `anyfin.{DATABASE_NAME}.{table_name}_raw` (added _raw). Because otherwise you are comparing a non-deduplicated table against a deduplicated one

2022-02-22 16:11 UTC, malcolmtivelius requested changes
Added some comments that I think we should take a look at before merging

2022-02-23 07:58 UTC, csioa commented on anyfin-platform/platform-composer/backfill-beam/buildDataflowTemplate.sh
> +    "main|assessment_reviews|offset|100000|created_at"
This is a good point and worth including in this PR. Will look into it

2022-02-23 08:12 UTC, csioa commented on anyfin-platform/platform-composer/dags/cloudsql_to_bigquery/export_bq_backfill.py
> +		daily_load = True if table_name in daily_tables else False
Yes, good catch. It actually seems that we have no daily_tables anymore, so I changed this to a more simplified version

2022-02-23 10:51 UTC, csioa commented on anyfin-platform/platform-composer/backfill-beam/buildDataflowTemplate.sh
> +schemas_file="../dags/cloudsql_to_bigquery/pg_schemas/${DB}_schemas_state.json"
@malcolmtivelius have a look at this one. this will fetch the configurations we need from the pg schemas state file and build the templates. we just need to give the db name as a parameter to run the script

2022-02-24 12:10 UTC, malcolmtivelius approved these changes
Lets do some backfilling!!

2022-02-24 12:40 UTC, merged